# Generated by Django 2.2.24 on 2021-12-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(error_messages={'required': 'Por favor, escreva algo'}, max_length=255),
        ),
    ]
